# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74dc989a3925957a1c01929dcf3a59e4dd7697ac8d0b35c73dca196900ecfda9d1ffce8c9c70ea2a67e87dd7dc13152f570b5a45589720e80a0d6b0e66888c19

test:
  secret_key_base: 4f8f67d15d2c447139a8703623dc800f2a067642d37448b390e80d809c617ad8246fb465d828a73c9874b8ead416594dae723d0c9ba50329be250d26def40e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
